// This file is automatically generated from the Play Games Console resources.
// Keep the class name GPGSIds; Google Play Games setup may regenerate this file.
public static class GPGSIds
{
    public const string app_id = "501257772338";
    public const string package_name = "com.youngdevstudios.fatefulrush";
    public const string achievement_first_rush = "CgkIsrqqqssOEAIQJw";
    public const string achievement_warming_up = "CgkIsrqqqssOEAIQBA";
    public const string achievement_halfway_there = "CgkIsrqqqssOEAIQGw";
    public const string achievement_no_turning_back = "CgkIsrqqqssOEAIQAg";
    public const string achievement_fate_defied = "CgkIsrqqqssOEAIQDA";
    public const string achievement_close_call = "CgkIsrqqqssOEAIQGQ";
    public const string achievement_thread_the_needle = "CgkIsrqqqssOEAIQGg";
    public const string achievement_living_on_the_edge = "CgkIsrqqqssOEAIQIA";
    public const string achievement_untouchable = "CgkIsrqqqssOEAIQIw";
    public const string achievement_combo_master = "CgkIsrqqqssOEAIQCg";
    public const string achievement_magnetic_attraction = "CgkIsrqqqssOEAIQCQ";
    public const string achievement_first_contact = "CgkIsrqqqssOEAIQHg";
    public const string achievement_divide_and_conquer = "CgkIsrqqqssOEAIQFQ";
    public const string achievement_behind_cover = "CgkIsrqqqssOEAIQCw";
    public const string achievement_dark_fate = "CgkIsrqqqssOEAIQDg";
    public const string achievement_golden_fate = "CgkIsrqqqssOEAIQHQ";
    public const string achievement_still_standing = "CgkIsrqqqssOEAIQBQ";
    public const string achievement_too_stubborn_to_quit = "CgkIsrqqqssOEAIQCA";
    public const string achievement_echo_initiate = "CgkIsrqqqssOEAIQAw";
    public const string achievement_double_trouble = "CgkIsrqqqssOEAIQDw";
    public const string achievement_shadow_army = "CgkIsrqqqssOEAIQJQ";
    public const string achievement_quick_reflexes = "CgkIsrqqqssOEAIQHw";
    public const string achievement_blink_and_you_miss_me = "CgkIsrqqqssOEAIQHA";
    public const string achievement_born_to_rush = "CgkIsrqqqssOEAIQIg";
    public const string achievement_counterattack = "CgkIsrqqqssOEAIQAQ";
    public const string achievement_payback = "CgkIsrqqqssOEAIQGA";
    public const string achievement_reaper = "CgkIsrqqqssOEAIQBg";
    public const string achievement_pocket_change = "CgkIsrqqqssOEAIQFg";
    public const string achievement_treasure_hunter = "CgkIsrqqqssOEAIQJA";
    public const string achievement_fortune_favors_the_fast = "CgkIsrqqqssOEAIQFA";
    public const string achievement_suit_up = "CgkIsrqqqssOEAIQBw";
    public const string achievement_iron_resolve = "CgkIsrqqqssOEAIQDQ";
    public const string achievement_time_bender = "CgkIsrqqqssOEAIQEQ";
    public const string achievement_master_of_time = "CgkIsrqqqssOEAIQKA";
    public const string achievement_bad_step = "CgkIsrqqqssOEAIQFw";
    public const string achievement_bomb_magnet = "CgkIsrqqqssOEAIQIQ";
    public const string achievement_ground_zero = "CgkIsrqqqssOEAIQEA";
    public const string achievement_burned_once = "CgkIsrqqqssOEAIQEg";
    public const string achievement_light_show_casualty = "CgkIsrqqqssOEAIQJg";
    public const string achievement_laserproof = "CgkIsrqqqssOEAIQEw";
}
